### ISSUE TITLE
Connecting to TheHive

### ISSUE THREAD

**Issue by xme** [CIRCL/AIL-framework#285]
I'm trying to enable the creation of some alerts in a instance of TheHive. I'm facing 2 issues at the moment.

An error message while trying to connect to my TheHive instance:

```
Connected to The HIVE: https://<redacted>
Traceback (most recent call last):
  File "./MISP_The_Hive_feeder.py", line 190, in <module>
    if int(r_serv_db.get('hive:auto-alerts')) == 1:
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

```
When I visit the page (http://ail.esx.rootshell.be:7000/PasteSubmit/edit_tag_export) to enable alerts based on tags, I don't see the newly created tags (personal ones). How can I "refresh" the list?

/x

**Comment by Terrtia** [comment]
Hey @xme 

Thank for the report !
Should be fixed with dad0365c67baf6e936f610f26ded1e5e87f2b103

Only the infoleak taxonomie is enabled by default. You need to add your custom tags in [Flask_server.py](https://github.com/CIRCL/AIL-framework/blob/master/var/www/Flask_server.py)

```python
# ========== INITIAL tags auto export ============
r_serv_db = redis.StrictRedis(
    host=cfg.get("ARDB_DB", "host"),
    port=cfg.getint("ARDB_DB", "port"),
    db=cfg.getint("ARDB_DB", "db"),
    decode_responses=True)
infoleak_tags = taxonomies.get('infoleak').machinetags()
infoleak_automatic_tags = []
for tag in taxonomies.get('infoleak').machinetags():
    if tag.split('=')[0][:] == 'infoleak:automatic-detection':
        r_serv_db.sadd('list_export_tags', tag)

r_serv_db.sadd('list_export_tags', 'infoleak:submission="manual"')
r_serv_db.sadd('list_export_tags', '<Your_Custum_Tag>')
```

I will add a more simple way to do it with #274. The news tags created with term management or regex.cfg should be added when created.

**Comment by xme** [comment]
Tx for the tip. Added my custom tags, testing now!

**Comment by xme** [comment]
Hmmm, I'm still facing this error (now my list of tags to be exported is ok)

`Connected to The HIVE: https://xxxxxxx
Traceback (most recent call last):
  File "./MISP_The_Hive_feeder.py", line 190, in <module>
    if int(r_serv_db.get('hive:auto-alerts')) == 1:
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

**Comment by xme** [comment]
Ok, it seems that the error above was related to the fact that TheHive was not enabled in the config. A restart of the script fixed it but it seems that there is a bug with the tag 'onion':

`DEBUG: infoleak:automatic-detection="phone-number" - /opt/AIL-framework/PASTES/crawled/2018/11/03/center222xdihudu.oniond97cf1f5-b279-41cf-ae49-b3e4cffa280e
DEBUG: infoleak:automatic-detection="pgp-message" - /opt/AIL-framework/PASTES/archive/pastebin.com_pro/2018/11/07/M6QBANGf.gz
DEBUG: infoleak:submission="crawler" - /opt/AIL-framework/PASTES/crawled/2018/11/03/ccbuddfko77ictab.oniond1e617c7-5f32-41bb-81d1-25638e762fa6
DEBUG: infoleak:submission="crawler" - /opt/AIL-framework/PASTES/crawled/2018/11/05/6gua6qlq3scz7jam.oniond2d39927-66a0-4f80-bf5b-35b01ec63484
DEBUG: infoleak:automatic-detection="onion" - crawled/2018/11/03/error.facebookcorewwwi.onion9ed31fb1-a3e3-48b6-9e78-65e972c7e53c
Traceback (most recent call last):
  File "./MISP_The_Hive_feeder.py", line 183, in <module>
    paste = Paste.Paste(path)
  File "/opt/AIL-framework/bin/packages/Paste.py", line 87, in __init__
    self.p_size = round(os.path.getsize(self.p_path)/1024.0, 2)
  File "/opt/AIL-framework/AILENV/lib/python3.5/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: 'crawled/2018/11/03/error.facebookcorewwwi.onion9ed31fb1-a3e3-48b6-9e78-65e972c7e53c'`

For all events tagged as 'onion', the path is not correct...

**Comment by xme** [comment]
I just upgraded to the latest version of the code and I still get errors (but less often):

`Traceback (most recent call last):
  File "./MISP_The_Hive_feeder.py", line 195, in <module>
    paste = Paste.Paste(path)
  File "/opt/AIL-framework/bin/packages/Paste.py", line 94, in __init__
    self.p_size = round(os.path.getsize(self.p_path)/1024.0, 2)
  File "/opt/AIL-framework/AILENV/lib/python3.5/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/opt/AIL-framework/PASTES/crawled/2018/11/08/dumpscciolcwmacb.onion8f5a7dfc-bb60-4c91-a6e8-015e8e159b80'
`
What is strange: when I checked the file (later, after I detected the issue), the file was present on the filesystem!? Something like a race condition problem?

**Comment by Terrtia** [comment]
You right, some pastes are tagged before the Mixer module save them on the disk

Should be solve with c3903ab203a197bb6106fb88a3a11546f661ff68

**Comment by xme** [comment]
Applied the changes located and I confirm it's fixed now! Keep up the good work!
