### ISSUE TITLE
LAUNCH.sh -u is not working if auto_update = False

### ISSUE THREAD

**Issue by ttuuxxeerr** [CIRCL/AIL-framework#443]
Hi,

I am wondering if this is a bug or a feature. I wanted to configure my AIL to avoid to be updated every time I need to start it. However if I disable the auto_update I can not manually update it using the option -u in the LAUNCH script having the following warning: 

```

******************************************************************
*                        Updating AIL ...                        *
******************************************************************
               AIL Auto update is disabled

Aborting ...
******************************************************************
*                    AIL Not Updated                             *
******************************************************************

```

**Comment by Terrtia** [comment]
Hi @ttuuxxeerr !
This is indeed a bug.
Fixed with 362afc225398c2064beb0740b876aa83ae4c4a74
Thanks!

**Comment by ttuuxxeerr** [comment]
Great, I tested and it works now. Cheers

**Comment by expl0i13r** [comment]
Hi i tried the same.

I am still getting same error and web interface doesnt start.

I tried changing the auto update setting in config but not working.

Anything else I can try?
