### ISSUE TITLE
Auto Installation Error : During update_thirdparty.sh

### ISSUE THREAD

**Issue by Nedfire2347** [CIRCL/AIL-framework#473]
Hello, I got a problem during AIL installation on a fresh ISO Ubuntu Bionic Beaver (18.04 LTS) (GNU/Linux 4.15.0-45-generic x86_64 )

_installing_deps.sh_ had an error during _/var/www/update_thirdparty.sh_

**Code Failure : Breakpoint**
/AILENV/bin/python3 /AILENV/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-6qyc5c/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'poetry>=0.12'

Is there a particular process for installation ?  Thanks for reading 
```
# ./update_thirdparty.sh

ERROR: Command errored out with exit status 1:

     command: /AILENV/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yu8dig9r/pyrsistent/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yu8dig9r/pyrsistent/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-yu8dig9r/pyrsistent/pip-egg-info
         cwd: /tmp/pip-install-yu8dig9r/pyrsistent/
    Complete output (30 lines):
    Traceback (most recent call last):
      File "/AILENV/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2698, in get_entry_map
        ep_map = self._ep_map
      File "/AILENV/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2669, in __getattr__
        raise AttributeError(attr)
    AttributeError: _ep_map
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-yu8dig9r/pyrsistent/setup.py", line 90, in <module>
        package_data={'pyrsistent': ['py.typed', '__init__.pyi', 'typing.pyi']},
      File "/AILENV/lib/python3.6/site-packages/setuptools/__init__.py", line 143, in setup
        _install_setup_requires(attrs)
      File "/AILENV/lib/python3.6/site-packages/setuptools/__init__.py", line 132, in _install_setup_requires
        (k, v) for k, v in attrs.items()
      File "/AILENV/lib/python3.6/site-packages/setuptools/dist.py", line 445, in __init__
        for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'):
      File "/AILENV/lib/python3.6/site-packages/pkg_resources/__init__.py", line 645, in iter_entry_points
        entries = dist.get_entry_map(group)
      File "/AILENV/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2701, in get_entry_map
        self._get_metadata('entry_points.txt'), self
      File "/AILENV/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2416, in parse_map
        maps[group] = cls.parse_group(group, lines, dist)
      File "/AILENV/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2394, in parse_group
        ep = cls.parse(line, dist)
      File "/AILENV/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2372, in parse
        raise ValueError(msg, src)
    ValueError: ("EntryPoint must be in 'name=module:attrs [extras]' format", 'pytaxonomies=bin/pytaxonomies')
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
`

**Comment by Terrtia** [comment]
Hi @Nedfire2347 !
Thank for the report !

Should be fixed with 07e3bfe

you need to relaunch it to complete the installation:
```bash
cd bin
./LAUNCH -t
```

**Comment by Nedfire2347** [comment]
Thanks for your reply ! 
Just some errors are still here but it works ! 

ERROR: peepdf 0.4.2 has requirement colorama==0.3.7, but you'll have colorama 0.4.3 which is incompatible. 
ERROR: peepdf 0.4.2 has requirement Pillow==3.2.0, but you'll have pillow 7.0.0 which is incompatible. 
ERROR: sflock 0.3.10 has requirement click==6.6, but you'll have click 7.0 which is incompatible.
ERROR: sflock 0.3.10 has requirement python-magic==0.4.12, but you'll have python-magic 0.4.15 which is incompatible.

**Comment by BeRambo** [comment]
> Thanks for your reply !
> Just some errors are still here but it works !
> 
> ERROR: peepdf 0.4.2 has requirement colorama==0.3.7, but you'll have colorama 0.4.3 which is incompatible.
> ERROR: peepdf 0.4.2 has requirement Pillow==3.2.0, but you'll have pillow 7.0.0 which is incompatible.
> ERROR: sflock 0.3.10 has requirement click==6.6, but you'll have click 7.0 which is incompatible.
> ERROR: sflock 0.3.10 has requirement python-magic==0.4.12, but you'll have python-magic 0.4.15 which is incompatible.

`pip install -r requirements.txt`

should fix that

**Comment by Terrtia** [comment]
Fixed
